yarnPath: .yarn/releases/yarn-4.1.1.cjs
nodeLinker: node-modules

npmRegistries:
  https://npm.greensock.com:
    npmAuthToken: "b5fe5405-22ea-4c3b-a8f0-830ff14eb8c8"
    npmAlwaysAuth: true

npmScopes:
  gsap:
    npmRegistryServer: "https://npm.greensock.com"
    npmAuthToken: "b5fe5405-22ea-4c3b-a8f0-830ff14eb8c8"
    npmAlwaysAuth: true